### ISSUE TITLE
Uncaught RuntimeException

### ISSUE THREAD

**Issue by sy92** [elastic/examples#204]
I get this error after the command:
`$ php seed.php`

`PHP Fatal error:  Uncaught RuntimeException: Elasticsearch-PHP requires cURL, or a custom HTTP handler. in /home/sy92/Documents/Elastic/Recipe_Search_PHP/examples-master/Search/recipe_search_php/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ClientBuilder.php:185
Stack trace:
#0 /home/sy92/Documents/Elastic/Recipe_Search_PHP/examples-master/Search/recipe_search_php/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ClientBuilder.php(452): Elasticsearch\ClientBuilder::defaultHandler()
#1 /home/sy92/Documents/Elastic/Recipe_Search_PHP/examples-master/Search/recipe_search_php/data/seed.php(17): Elasticsearch\ClientBuilder->build()
#2 {main}
  thrown in /home/sy92/Documents/Elastic/Recipe_Search_PHP/examples-master/Search/recipe_search_php/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ClientBuilder.php on line 185
`

**Comment by dyanakiev** [comment]
I have similar error:

```
Fatal error: Uncaught Elasticsearch\Common\Exceptions\BadRequest400Exception: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"The bulk request must be terminated by a newline [\n]"}],"type":"illegal_argument_exception","reason":"The bulk request must be terminated by a newline [\n]"},"status":400} in /Users/dimitaryanakiev/examples-master/Search/recipe_search_php/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:610
```

macOS PHP 7.1.12

**Comment by goupadhy** [comment]
replace implode("\n", $batchLines); with  implode("\n", $batchLines) . "\n" 
hope it will help someone :)

**Comment by brigi0627** [comment]
> replace implode("\n", $batchLines); with implode("\n", $batchLines) . "\n"
> hope it will help someone :)

This solved the issue for me, thank you!

**Comment by issacMontes28** [comment]
> > replace implode("\n", $batchLines); with implode("\n", $batchLines) . "\n"
> > hope it will help someone :)
> 
> This solved the issue for me, thank you!

I'm facing the same problem, in which file did you change that line. Thanks in advance for your help.

**Comment by brigi0627** [comment]
> > > replace implode("\n", $batchLines); with implode("\n", $batchLines) . "\n"
> > > hope it will help someone :)
> > 
> > 
> > This solved the issue for me, thank you!
> 
> I'm facing the same problem, in which file did you change that line. Thanks in advance for your help.

seed.php should be the name of the file
